---
- name: Deploy app
  hosts: webserver
  become: yes
  tasks:
  - name: Install NGINX web server
    package:
      name: nginx
      state: present
  - name: Copy source copy to webserver
    copy:
      scr: app-src/
      dest: /svr/app/
    notify: Restart NGINX service
  - name: Enable NIGNX service
    service: nginx
    enabled: yes
    state: started
  - name: Setup NGINX for the app
    template:
      scr: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
    notify: Restart NGINX service
  handlers:
  - name: Restart NGINX service
    service
      name: nginx
      state: restarted
